<a href="https://colab.research.google.com/github/Joecsr24/this_is_the_way/blob/main/DL_csr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!df -h

Filesystem      Size  Used Avail Use% Mounted on
overlay         108G   39G   70G  36% /
tmpfs            64M     0   64M   0% /dev
tmpfs           6.4G     0  6.4G   0% /sys/fs/cgroup
shm             5.9G     0  5.9G   0% /dev/shm
tmpfs           6.4G   24K  6.4G   1% /var/colab
/dev/sda1       114G   41G   74G  36% /etc/hosts
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware


In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2299.998
cache size	: 46080 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 4599.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	:

In [ ]:
!cat /proc/meminfo

MemTotal:       13305324 kB
MemFree:        10323520 kB
MemAvailable:   12437196 kB
Buffers:           88736 kB
Cached:          2152540 kB
SwapCached:            0 kB
Active:          1039316 kB
Inactive:        1703832 kB
Active(anon):     459140 kB
Inactive(anon):      420 kB
Active(file):     580176 kB
Inactive(file):  1703412 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               136 kB
Writeback:             0 kB
AnonPages:        501884 kB
Mapped:           346340 kB
Shmem:              1164 kB
KReclaimable:     143328 kB
Slab:             188264 kB
SReclaimable:     143328 kB
SUnreclaim:        44936 kB
KernelStack:        4320 kB
PageTables:         6404 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6652660 kB
Committed_AS:    3314228 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        6720 kB
VmallocChunk:          0 kB
Percpu:          

In [ ]:
# 
#Session 1  张量的创建及常用方法
# 

In [ ]:
import torch
torch.__version__

'1.8.1+cu101'

In [ ]:
# 1.1 tensor基本创建及其类型

In [ ]:
# tensor函数创建方法

# 通过列表创建
t = torch.tensor([1,2])
t

tensor([1, 2])

In [ ]:
# 通过元组创建
t1 = torch.tensor((1,2))
t1

tensor([1, 2])

In [ ]:
# 通过数组进行创建
import numpy as np
a = np.array((1,2))
t2 = torch.tensor(np.array((1,2)))
t2

tensor([1, 2])

In [ ]:
# tensor的类型

In [ ]:
[t.dtype, t1.dtype, t2.dtype] 

torch.tensor(np.array((1.1, 2.2))), torch.tensor([1.11, 2.2]).dtype

torch.tensor([True, False]).dtype

torch.tensor([1.1, 2.2], dtype=torch.int16)

tensor([1, 2], dtype=torch.int16)

In [ ]:
# 张量类型的转化

In [ ]:
# 隐式转化

torch.tensor((2, 1.4)), torch.tensor((True, 3.3))

# float & double转化

torch.tensor((1,2)).float(), torch.tensor((2,3)).double()

(tensor([1., 2.]), tensor([2., 3.], dtype=torch.float64))

In [ ]:
# 1.2 张量的维度和形变

In [ ]:
# 创建高位张量 查看维度和形状

torch.tensor([1.2, 2.3]).ndim ,  torch.tensor((1.2, 2.3)).shape

(1, torch.Size([2]))

In [ ]:
# 返回有几个n-1维的元素
len(torch.tensor([1.1, 2.2, 3.3]))

# 返回总共有几个数字
torch.tensor([1.2,2.3,3.4,4.5]).numel()

# list的list创建
t2=torch.tensor([[1,2],[3,4]])
t2, t2.ndim, t2.shape, len(t2), t2.numel()

(tensor([[1, 2],
         [3, 4]]), 2, torch.Size([2, 2]), 2, 4)

In [ ]:
# 高维张量
a1=np.array([[1,2,2],[3,4,4]]) 
a1
a2=np.array([[5,6,6],[7,8,8]])
a2

# 由两个形状相同的3维数组创建一个3维的张量
t3=torch.tensor([a1, a2])
t3
# t3.ndim, t3.shape, len(t3), t3.numel()


tensor([[[1, 2, 2],
         [3, 4, 4]],

        [[5, 6, 6],
         [7, 8, 8]]])

In [ ]:
# flatten 拉平：将任意维度张量转化为一维张量
t3.flatten()

# reshape:任意变形
t3.reshape(12,)

tensor([1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8])

In [ ]:
# 1.3 特殊张量的创建方法

In [ ]:
# 全0张量
torch.zeros([3,2])

# 全1张量
torch.ones([2,3])

# 单位阵
torch.eye(5)

# 对角矩阵  不能使用list直接创建对角矩阵，必须使用tensor
torch.diag(torch.tensor([2,4,6,8]))

# rand:服从均分分布的张量
torch.rand([3,2])

# randn:服从标准正态分布的张量
torch.randn([3,4])

# normal:服从正态分布的张量 均值为2，std为3的normal
torch.normal(2,3,size=(2,3,4))

# randint:整数随机采样
torch.randint(0,10,size=(2,4,5))

# arange/linspace生成数列
torch.arange(1,5), torch.arange(1,5,0.5), torch.linspace(1,5,4)

# empty:生成未初始化的指定形状矩阵
torch.empty([3,4])

# full:根据指定形状，填充指定数值
torch.full([3,4],521)

tensor([[521, 521, 521, 521],
        [521, 521, 521, 521],
        [521, 521, 521, 521]])

In [ ]:
# 创建指定形状的数组 _like前后张量数据类型应一致
torch.full_like(torch.tensor([[[2,2,3],[1,2,4],[5,4,7]]]) , 521 ), torch.randint_like(torch.tensor([[1,2],[2,3]]),5,10), 
torch.zeros_like(torch.tensor([1,2])), torch.randn_like(torch.tensor([2.0, 5.0]))

(tensor([0, 0]), tensor([-1.0496, -2.1646]))

In [ ]:
# 1.4 张量和其他相关类型之间的转化方法

In [ ]:
# numpy:张量转数组    tensor to array
t1=torch.tensor([[1,2],[3,4]]) 
t1.numpy(), np.array(t1)

# tolist:张量转列表 tensor to list  注意区分tolist()和list()
t1.tolist()
list(t1)

# item:转化为数值 只能转化one element
torch.tensor([2]).item()

2

In [ ]:
# 1.5 张量的深拷贝

In [ ]:
# 如果只用等号则是浅拷贝，改变一个另一个也会变；使用clone则是深拷贝，改变一个另一个不会变，两者相互独立
t10=t1.clone()
t10[0]

tensor([1, 2])

In [ ]:
# 
#Session 2  张量的索引、分片合并以及维度调整
# 

In [1]:
# 2.1 张量的符号索引

In [7]:
# 一维张量索引  索引出来还是张量，如需转标量用item
t1=torch.arange(1,11)
t1[-1].item()

10